name: neobis_flutter_rick_and_morty_rodion
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  flutter_svg: ^2.0.7
  flutter_gen: ^5.3.2
  rick_and_morty_api: ^0.1.2
  # rick_and_morty_api: ^0.1.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.8
  # flutter_gen_runner:
  slang_build_runner: ^3.30.0
  auto_route_generator: ^7.3.2
 

flutter_gen:
  integrations:
    flutter_svg: true



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

